name: Audit
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  js:
    name: Audit JS Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/npm/cli/issues/2610
      #
      # For `github:hyperbola/logo` dependency.
      # See: https://github.com/hyperbola/hyperbola-static/pull/267
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Install Nodejs toolchain
        run: npm ci

      - name: npm audit
        run: npm audit
